<?php

return [
    'fields.allergens' => '过敏原',
    'fields.attachments' => '附件',
    'fields.boundaries' => '边界',
    'fields.branch' => '分支',
    'fields.category' => '部分',
    'fields.category_id' => '部分',
    'fields.category_name' => '类别名称',
    'fields.created_from' => '创建日期自',
    'fields.data.address' => '地址',
    'fields.data_dimensions' => '尺寸',
    'fields.data_lock_kitchen' => '将厨房锁在天花板上',
    'fields.date_from' => '日期',
    'fields.date_until' => '日期到',
    'fields.debug_mode' => '激活调试模式',
    'fields.delivery_method' => '发货方式',
    'fields.design_image' => '设计形象',
    'fields.design_pattern_title' => '风格',
    'fields.dimensions' => '长：宽：宽：高',
    'fields.disabled' => '残疾人',
    'fields.is_paid' => '有薪酬的',
    'fields.manager_id' => '老板',
    'fields.notification_body.ar' => '通知文本为阿拉伯语',
    'fields.notification_body.en' => '通知文本为英文',
    'fields.notification_title.ar' => '阿拉伯语通知标题',
    'fields.notification_title.en' => '通知英文标题',
    'fields.offers' => '引号',
    'fields.orders_discount_upon_receipt_from_the_branch' => '从分行收到订单时的折扣值',
    'fields.otp_code_is_random' => '随机验证码',
    'fields.pattern_category_name' => '类别名称',
    'fields.pattern_id' => '风格',
    'fields.pattern_title' => '类别',
    'fields.place_type' => '设计类型',
    'fields.sale_price' => '售价',
    'fields.translatable' => '相关内容...',
    'fields.working_days' => '工作日'
];
