<?php

return [
    'fields.allergens' => 'Allergene',
    'fields.attachments' => 'Anhänge',
    'fields.boundaries' => 'Grenze',
    'fields.branch' => 'Zweig',
    'fields.category' => 'Abschnitt',
    'fields.category_id' => 'Abschnitt',
    'fields.category_name' => 'Kategoriename',
    'fields.created_from' => 'Erstellungsdatum von',
    'fields.data.address' => 'die Adresse',
    'fields.data_dimensions' => 'Größen',
    'fields.data_lock_kitchen' => 'Die Küche an der Decke befestigen...',
    'fields.date_from' => 'Datum von',
    'fields.date_until' => 'Datum bis',
    'fields.debug_mode' => 'Aktivieren Sie den Debug-Modus',
    'fields.delivery_method' => 'Versandart',
    'fields.design_image' => 'Designbild',
    'fields.design_pattern_title' => 'Stil',
    'fields.dimensions' => 'LÄNGE:BREITE:BREITE:HÖHE',
    'fields.disabled' => 'Deaktiviert',
    'fields.is_paid' => 'bezahlt',
    'fields.manager_id' => 'der Chef',
    'fields.notification_body.ar' => 'Der Text der Bekanntmachung ist auf Arabisch',
    'fields.notification_body.en' => 'Der Text der Mitteilung ist auf Englisch',
    'fields.notification_title.ar' => 'Hinweistitel auf Arabisch',
    'fields.notification_title.en' => 'Hinweistitel auf Englisch',
    'fields.offers' => 'Zitate',
    'fields.orders_discount_upon_receipt_from_the_branch' => 'La valeur de la remise pour les commandes à réception en agence',
    'fields.otp_code_is_random' => 'Zufälliger Bestätigungscode',
    'fields.pattern_category_name' => 'Kategoriename',
    'fields.pattern_id' => 'Stil',
    'fields.pattern_title' => 'Stil',
    'fields.place_type' => 'Designtyp',
    'fields.sale_price' => 'Verkaufspreis',
    'fields.translatable' => 'Weitere Informationen',
    'fields.working_days' => 'Arbeitstage'
];
