<?php

return [
    'fields.allergens' => 'Allergènes',
    'fields.attachments' => 'Pièces jointes',
    'fields.boundaries' => 'frontière',
    'fields.branch' => 'Bifurquer',
    'fields.category' => 'Section',
    'fields.category_id' => 'Section',
    'fields.category_name' => 'Nom de la catégorie',
    'fields.created_from' => 'Date de création du',
    'fields.data.address' => 'l\'adresse',
    'fields.data_dimensions' => 'Tailles',
    'fields.data_lock_kitchen' => 'Verrouiller la cuisine au plafond',
    'fields.date_from' => 'Date de',
    'fields.date_until' => 'date à',
    'fields.debug_mode' => 'Activer le mode débogage',
    'fields.delivery_method' => 'Mode de livraison',
    'fields.design_image' => 'Image de conception',
    'fields.design_pattern_title' => 'Style',
    'fields.dimensions' => 'LONGUEUR:LARGEUR:LARGEUR:HAUTEUR',
    'fields.disabled' => 'Désactivé',
    'fields.is_paid' => 'payé',
    'fields.manager_id' => 'le patron',
    'fields.notification_body.ar' => 'Le texte de l\'avis est en arabe',
    'fields.notification_body.en' => 'Le texte de l\'avis est en anglais',
    'fields.notification_title.ar' => 'Titre de la notice en arabe',
    'fields.notification_title.en' => 'Titre de la notice en anglais',
    'fields.offers' => 'Citations',
    'fields.orders_discount_upon_receipt_from_the_branch' => 'La valeur de la remise pour les commandes à réception en agence',
    'fields.otp_code_is_random' => 'Code de vérification aléatoire',
    'fields.pattern_category_name' => 'Nom de la catégorie',
    'fields.pattern_id' => 'Style',
    'fields.pattern_title' => 'Style',
    'fields.place_type' => 'Type de conception',
    'fields.sale_price' => 'prix de vente',
    'fields.translatable' => 'Multilingue',
    'fields.working_days' => 'jours ouvrables'
];
