<?php

return [
    'fields.allergens' => 'Allergens',
    'fields.attachments' => 'Attachments',
    'fields.boundaries' => 'border',
    'fields.branch' => 'Branch',
    'fields.category' => 'Section',
    'fields.category_id' => 'Section',
    'fields.category_name' => 'Category name',
    'fields.created_from' => 'Creation date from',
    'fields.data.address' => 'the address',
    'fields.data_dimensions' => 'Sizes',
    'fields.data_lock_kitchen' => 'Locking the kitchen to the ceiling',
    'fields.date_from' => 'Date of',
    'fields.date_until' => 'date to',
    'fields.debug_mode' => 'Activate debug mode',
    'fields.delivery_method' => 'Delivery method',
    'fields.design_image' => 'Design image',
    'fields.design_pattern_title' => 'Style',
    'fields.dimensions' => 'LENGTH:WIDTH:WIDTH:HEIGHT',
    'fields.disabled' => 'Disabled',
    'fields.is_paid' => 'paid',
    'fields.manager_id' => 'the boss',
    'fields.notification_body.ar' => 'The text of the notice is in Arabic',
    'fields.notification_body.en' => 'The text of the notice is in English',
    'fields.notification_title.ar' => 'Notice title in Arabic',
    'fields.notification_title.en' => 'Notice title in English',
    'fields.offers' => 'Quotes',
    'fields.orders_discount_upon_receipt_from_the_branch' => 'The discount value for orders upon receipt from the branch',
    'fields.otp_code_is_random' => 'Random verification code',
    'fields.pattern_category_name' => 'Category name',
    'fields.pattern_id' => 'Style',
    'fields.pattern_title' => 'Style',
    'fields.place_type' => 'Design type',
    'fields.sale_price' => 'selling price',
    'fields.translatable' => 'Multilingual',
    'fields.working_days' => 'working days'
];
